permissions:
  player: 200
  vip: 400

messages:
  header: "<#FFD700>Nearby players within <#FFFFFF>{radius} <#FFD700>blocks:"
  no-players: "<#FF5555>No one nearby."
  player-line: "<#55FF55>* {arrow} {player} - {distance} blocks."
  hover-text: "Click to interactpp"
  click-command: "/invsee {player}"
  no-custom-radius: "<#FF5555>You need permission to use custom radius!"
  invalid-radius: "<#FF5555>Radius must be 1-1000 blocks!"
  invalid-number: "<#FF5555>Invalid number!"
  usage: "<#FF5555>/near or /near <radius>"


arrows:
  north: "⬆"
  north-east: "⬈"
  east: "➜"
  south-east: "⬊"
  south: "⬇"
  south-west: "⬋"
  west: "⬅"
  north-west: "⬉"

sounds:
  enabled: true
  found-players:
    sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 1.0
    pitch: 1.0
  no-players:
    sound: "BLOCK_NOTE_BLOCK_BASS"
    volume: 1.0
    pitch: 0.5